name: "Deploy PoC Env (IaC)"

on: workflow_dispatch

jobs:
  deploy-poc-env:
    #env:
       #GOOGLE_CREDENTIALS: ${{ secrets.GCP_CREDENTIALS }}
  
    name: "Deploy PoC Env"
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: "./IaC/PoC"
    
    steps:
      - name: Checkout
        uses: actions/checkout@v2

      - name: Setup Terraform
        uses: hashicorp/setup-terraform@v1
        with:
          # terraform_version: 0.13.0:
          cli_config_credentials_token: ${{ secrets.TF_API_TOKEN }}

      - name: Terraform Format
        id: fmt
        run: terraform fmt -recursive

      - name: Terraform Init
        id: init
        run: terraform init

      - name: Terraform Plan
        id: plan
        run: terraform plan -no-color

      - name: Terraform Apply
        id: apply
        run: terraform apply -auto-approve
  
  create-issue:
    runs-on: ubuntu-latest
    if: ${{ failure() }}
    needs: deploy-poc-env
    steps:
      - name: create-issue
        uses: oaviles/issue_action@v1
        with:
          issue-title: "Deployment Failure: PoC Env - ${{ github.sha }}"
          issue-body: "Validate orchestration workflow"
          repo-token: ${{secrets.GITHUB_TOKEN}}    
